### ISSUE TITLE
Expose nemiver interface on pkg-config

### ISSUE THREAD

**Issue by albfan** [albfan/nemiver#6]
This compilations fails

https://github.com/albfan/gnome-builder/issues/4#issuecomment-256551094

will be fixed with:

https://bugzilla.gnome.org/show_bug.cgi?id=773575

meanwhile, using this fork as source should do the work

**Comment by albfan** [comment]
* uncomment https://github.com/albfan/nemiver/blob/master/src/common/Makefile.am#L82 to add to pkg-config
* isolate defines
* add needed headers

**Comment by albfan** [comment]
Use of pkg-config ready. See https://github.com/albfan/gnome-builder/commit/9e79ea2e6b24d754c38d78942b2cd88ee57b0f73

**Comment by albfan** [comment]
to isolate defines is needed that config.h to not be included

**Comment by hfiguiere** [comment]
When you are done, if you can squash all these commits in one, and attach it to the upstream bugzilla. We'll try to get it merge ASAP.

Thanks a lot !

**Comment by hfiguiere** [comment]
(and please see my comments)

**Comment by albfan** [comment]
@hfiguiere I have pkg-config working and libs are deployed to libdir directly, so gnome-builder debugger plugin find them correctly, please validate (commit is rebased on top of master).

**Comment by albfan** [comment]
I will continue process to integrate on gnome (through bugzilla) on issues left to do. This one is working
